const HTTP_STATUS = require('./httpStatus');
const { ROLES, ROLE_VALUES } = require('./roles');
const { PRODUCT_CATEGORIES, CATEGORY_VALUES } = require('./product');
const { RECORD_STATUS, STATUS_VALUES } = require('./status');
const {
  PET_SPECIES,
  SPECIES_VALUES,
  PET_GENDER,
  GENDER_VALUES,
  ADOPTION_STATUS,
  ADOPTION_STATUS_VALUES,
} = require('./pet');
const {
  BOOKING_STATUS,
  STATUS_VALUES: BOOKING_STATUS_VALUES,
  SERVICE_TYPES,
  SERVICE_VALUES,
} = require('./booking');
const { NOTIFICATION_TYPE, NOTIFICATION_TYPE_VALUES } = require('./notification');

module.exports = {
  HTTP_STATUS,
  ROLES,
  ROLE_VALUES,
  PRODUCT_CATEGORIES,
  CATEGORY_VALUES,
  RECORD_STATUS,
  STATUS_VALUES,
  PET_SPECIES,
  SPECIES_VALUES,
  PET_GENDER,
  GENDER_VALUES,
  ADOPTION_STATUS,
  ADOPTION_STATUS_VALUES,
  BOOKING_STATUS,
  BOOKING_STATUS_VALUES,
  SERVICE_TYPES,
  SERVICE_VALUES,
  NOTIFICATION_TYPE,
  NOTIFICATION_TYPE_VALUES,
};